env:
  global:
    Label: Taisia is beautiful

os: linux
dist: xenial
sudo: false
language: python
python: 3.6

install:
  - python --version
  - pip install conan
  - pip install nose2

script:
  - nose2 -v

