env:
  global:
    Label: Taisia is beautiful

linux: &linux_build
  os: linux
  dist: xenial
  sudo: false
  language: python
  python: 3.7

install:
  - pip install conan
  - pip install nose2

script:
  - nose2 -v
